name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      
      - name: Build with Maven
        run: mvn clean install
      
      
      - name: Access built artifacts
        run: ls target
        
      - name: Create artifact
        run: |
         mkdir artifacts
         cp target/my-project-1.0.0.jar artifacts/
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.release }}
        with:
         tag_name: v1.0.0
         release_name: Release v1.0.0
         body: |
         draft: false
         prerelease: false
        
        
      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
           upload_url: ${{ github.event.release.upload_url }}
           asset_path: ./artifacts
           asset_name: my-oroject-1.0.0.jar
           asset_content_type: application/jar


