name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Access built artifacts
        run: ls target
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: v1.0.0  
          release_name: Release v1.0.0  
          body: |
            Release notes for v1.0.0  # Replace with your release notes

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
         name: my-project-1.0.0.jar
         path: ./artifacts/  
