name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      
      - name: Build with Maven
        run: mvn clean install
      
      
      - name: Access built artifacts
        run: ls target
        
      - name: Create artifact
        run: |
         mkdir artifacts
         cp target/my-project-1.0.0.jar artifacts/
      
      
        
        
      - name: Get Release Upload URL
        id: release
        run: |
          upload_url=$(curl --header "Authorization: Bearer ${{ secrets.release }}" \
                  --header "Accept: application/vnd.github.v3+json" \
                  --silent \
                  "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}" \
                  | jq -r '.upload_url')
          echo "::set-output name=upload_url::$upload_url"

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
           upload_url: ${{ steps.release.outputs.upload_url }}
           asset_path: ./artifacts/
           asset_name: my-project-1.0.0.zip
           asset_content_type: application/java-archive

           
           


